version: '2'

networks:
    bibbox-default-network:
      external: true

services:

  §§INSTANCE-phenotips:
    image: bibbox/phenotips
    container_name:  §§INSTANCE-phenotips
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - §§INSTANCE-phenotips-db:phenotips-db
    ports:
      - "§§PORT:8080"
    depends_on:
      - §§INSTANCE-phenotips-db
      - §§INSTANCE-phenotips-data
    volumes_from: 
      - §§INSTANCE-phenotips-data

  §§INSTANCE-phenotips-db:
    image: mysql:8
    container_name: §§INSTANCE-phenotips-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=thispasswordisneverusedeveninsidethecontainer
      - MYSQL_DATABASE=phenotips
      - MYSQL_USER=phenotips
      - MYSQL_PASSWORD=phenotips4bibbox
    volumes_from: 
      - §§INSTANCE-phenotips-data
    depends_on:
      - §§INSTANCE-phenotips-data

  §§INSTANCE-phenotips-data:
    image: busybox
    container_name: §§INSTANCE-phenotips-data
    volumes:
      - ./var/lib/mysql:/var/lib/mysql
      - ./phenotips/extapi:/project/src 
