version: '2'
services:

  §§INSTANCE-phenotips:
    image: bibbox/phenotips
    container_name:  §§INSTANCE-phenotips
    links:
      - §§INSTANCE-phenotips-db::§§INSTANCE-phenotips-db
    ports:
      - "8098:8080"
    depends_on:
      - §§INSTANCE-phenotips-db
      - §§INSTANCE-phenotips-data
    volumes_from: 
      - §§INSTANCE-phenotips-data

  §§INSTANCE-phenotips-db:
    image: mysql
    container_name: §§INSTANCE-phenotips-db
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=§§MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=§§MYSQL_DATABASE
      - MYSQL_USER=§§MYSQL_USER
      - MYSQL_PASSWORD=§§MYSQL_PASSWORD
    volumes_from: 
      - §§INSTANCE-phenotips-data
    depends_on:
      - §§INSTANCE-phenotips-data

  §§INSTANCE-phenotips-data:
    image: busybox
    container_name: §§INSTANCE-phenotips-data
    volumes:
      - §§FOLDER/var/lib/mysql:/var/lib/mysql
      