version: '2'
services:

  §§INSTANCE-phenotips:
    image: bibbox/phenotips
    container_name:  §§INSTANCE-phenotips
    links:
      - §§INSTANCE-phenotips-db:§§INSTANCE-phenotips-db
    ports:
      - "§§PORT:8080"
    depends_on:
      - §§INSTANCE-phenotips-db
      - §§INSTANCE-phenotips-data
    volumes_from: 
      - §§INSTANCE-phenotips-data

  §§INSTANCE-phenotips-extapi:
    build: 
        context: ./images/phenotips-extapi
    image: bibbox/phenotips-extapi
    container_name:   §§INSTANCE-phenotips-extapi
    links:
      - §§INSTANCE-phenotips-data:phenotips
    depends_on:
      - §§INSTANCE-phenotips-data
    volumes_from: 
      - §§INSTANCE-phenotips-data
    ports:
      - "§§EXTAPI_PORT:8000"

  §§INSTANCE-phenotips-db:
    image: mysql
    container_name: §§INSTANCE-phenotips-db
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=§§MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=§§MYSQL_DATABASE
      - MYSQL_USER=§§MYSQL_USER
      - MYSQL_PASSWORD=§§MYSQL_PASSWORD
    volumes_from: 
      - §§INSTANCE-phenotips-data
    depends_on:
      - §§INSTANCE-phenotips-data

  §§INSTANCE-phenotips-data:
    image: busybox
    container_name: §§INSTANCE-phenotips-data
    volumes:
      - §§FOLDER/var/lib/mysql:/var/lib/mysql
      - §§FOLDER/phenotips/extapi:/project/src 
