version: '3.8'

networks:
    bibbox-default-network:
      external: true

services:

  §§INSTANCE-phenotips:
    image: bibbox/phenotips
    container_name:  §§INSTANCE-phenotips
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - §§INSTANCE-phenotips-db:phenotips-db
    ports:
      - "8080"
    depends_on:
      - §§INSTANCE-phenotips-db
    volumes: 
      - ./phenotips/extapi:/project/src 

  §§INSTANCE-phenotips-db:
    image: mariadb
    container_name: §§INSTANCE-phenotips-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=thispasswordisneverusedeveninsidethecontainer
      - MYSQL_DATABASE=§§MYSQLDATABASE
      - MYSQL_USER=§§MYSQLUSER
      - MYSQL_PASSWORD=§§MYSQLPASSWORD
    volumes: 
      - ./var/lib/mysql:/var/lib/mysql
