version: '2'
services:

  §§INSTANCE-phenotips:
    image: bibbox/phenotips
    container_name:  §§INSTANCE-phenotips
    links:
      - §§INSTANCE-phenotips-db:phenotips-db
    ports:
      - "§§PORT:8080"
    depends_on:
      - §§INSTANCE-phenotips-db
      - §§INSTANCE-phenotips-data
    volumes_from: 
      - §§INSTANCE-phenotips-data

  §§INSTANCE-phenotips-db:
    image: mysql
    container_name: §§INSTANCE-phenotips-db
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=thispasswordisneverusedeveninsidethecontainer
      - MYSQL_DATABASE=phenotips
      - MYSQL_USER=phenotips
      - MYSQL_PASSWORD=phenotips4bibbox
    volumes_from: 
      - §§INSTANCE-phenotips-data
    depends_on:
      - §§INSTANCE-phenotips-data

  §§INSTANCE-phenotips-data:
    image: busybox
    container_name: §§INSTANCE-phenotips-data
    volumes:
      - §§FOLDER/var/lib/mysql:/var/lib/mysql
      - §§FOLDER/phenotips/extapi:/project/src 
