version: '3'

networks:
    bibbox-default-network:
      external: true

services:
  bibbox-phenotips:
    image: bibbox/phenotips:1.4.9
    container_name:  bibbox-phenotips
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - bibbox-phenotips-db:phenotips-db
    ports:
      - "8010:8080"
    depends_on:
      - bibbox-phenotips-db
    volumes: 
      - ./data/phenotips/extapi:/project/src 
  bibbox-phenotips-db:
    image: mariadb:10.7.3
    container_name: bibbox-phenotips-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=thispasswordisneverusedeveninsidethecontainer
      - MYSQL_DATABASE=phenotips
      - MYSQL_USER=phenotips
      - MYSQL_PASSWORD=phenotips4bibbox
    volumes:
      - ./data/var/lib/mysql:/var/lib/mysql
     
