version: '2'
services:

  phenotips-debug:
    image: bibbox/phenotips
    container_name:  phenotips-debug
    links:
      - phenotips-db-debug:phenotips
    ports:
      - "8098:8080"
    depends_on:
      - phenotips-db-debug
      - phenotips-data-debug
    volumes_from: 
      - phenotips-data-debug

  phenotips-db-debug:
    image: mysql
    container_name: phenotips-db-debug
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=fenris
      - MYSQL_DATABASE=phenotips
      - MYSQL_USER=phenotips
      - MYSQL_PASSWORD=fenris
    volumes_from: 
      - phenotips-data-debug
    depends_on:
      - phenotips-data-debug

  phenotips-data-debug:
    image: busybox
    container_name: phenotips-data-debug
    volumes:
      - /Users/mue/dockerdata/phenotips/var/lib/mysql:/var/lib/mysql
      